export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SAVE_USER_INFO_SUCCESS = 'SAVE_USER_INFO_SUCCESS';
export const SAVE_USER_INFO_FAILED = 'SAVE_USER_INFO_FAILED';

export const SET_USER_INFO_FAILED = 'SET_USER_INFO_FAILED';

export const DELETE_USER_INFO = 'DELETE_USER_INFO';
export const DELETE_USER_INFO_SUCCESS = 'DELETE_USER_INFO_SUCCESS';
export const DELETE_USER_INFO_FAILED = 'DELETE_USER_INFO_FAILED';

export const CLEAR_SELECTED_USER_INFO = 'CLEAR_SELECTED_USER_INFO';

export const GET_USER_POSITIONS = 'GET_USER_POSITIONS';
export const GET_USER_POSITIONS_SUCCESS = 'GET_USER_POSITIONS_SUCCESS';
export const GET_USER_POSITIONS_FAILED = 'GET_USER_POSITIONS_FAILED';
